config/routes.rb
Rails.application.routes.draw do
  match "/users/remove_all", to: "users#remove_all", via: [:delete], as: :remove_all
  resources :users
  get 'index', to: 'hi#index'
  get 'about', to: 'hi#about'
  root 'hi#about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hi_controller.rb
class HiController < ApplicationController
  def index
    @time = Time.now
    @stud = 'Student'
    @message = ->(i){"Моє повідомлення #{i} прийшло з Контролера"}
  end
  def about

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def remove_all
    User.destroy_all

    respond_to do |format|
      format.html { redirect_to users_url, notice: "Users were successfully destroyed." }
      format.xml  { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hi_helper.rb
module HiHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hi/about.html.erb
<center><h3>Лабораторна робота № 9</h3>
<h4>Тема: Робота з компонентами MVC-RoR проекту</h4>
<p><b>Мета роботи</b> – навчитися створювати веб-аплікації із хедерами,
футерами та Bootstrap.</p>
<h4>9.1 Завдання для виконання</h4>
<p>В лабораторній роботі №8 було створено просту аплікацію для
реєстрування користувачів. В цій роботі потрібно додати зручності для
роботи з додатком і додати оформлення.</p>
<p>Послідовність виконання завдань:<br>
1. Відкрити проект ЛР8;<br>
2. Додати до проекту хедер і футер [1].<br>
3. У футері розмістити контактну інформацію про розробника.<br>
4. Приєднати до проекту фреймворк Bootstrap [2].<br>
5. Вибрати один із готових шаблонів в розділі Navs & Tabs [3],
розмістити його у хедері свого проекту.<br>
6. До пунктів навігації приєднати такі дії "Про проект", "Створити
користувача", "Показати всіх користувачів", "Видалити всіх користувачів".
Дія "Про проект" повинна відображати завдання до цієї лабораторної роботи.<br>
7. Видалити дії, які є на сторінках, і продубльовані в навбарі.<br></p>
<h4>9.3 Зміст звіту</h4>
<p>Звіт повинен містити:<br>
1) Тему, мету роботи;<br>
2) Всі фрагменти коду, які створені або модифіковані вами;<br>
3) Скріншоти роботи проекту у браузері;<br>
4) Cкріншот запущеного сервера із 2-3 відповідями;<br>
5) Покликання на GitHub цього проекту;<br>
6) Висновки.<br></p>
</center>

app/views/hi/index.html.erb
<html>
<head><title>Hi <%= @stud %>!</title></head>
<body>
<h1>Hello, <%= @stud %>!</h1>
<p>Це повідомлення прибуло з app/views/hi/index.html.erb</p>
<% 5.times do |i|%>
<p><%= @message.call(i) %></p>
<% end %>
<p><%= @time %></p>
</body>
</html>

app/views/layouts/_footer.html.erb
<footer class="text-muted py-5 fixed-bottom">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Anatolii Matskaniuk, Ivano-Frankivsk</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="container">
    <header class="d-flex justify-content-center py-3">
      <ul class="nav nav-pills">
        <li class="nav-item"><a href="<%= about_path %>" class="nav-link">Про проект</a></li>
        <li class="nav-item"><a href="<%= new_user_path %>" class="nav-link">Створити користувача</a></li>
        <li class="nav-item"><a href="<%= users_path %>" class="nav-link">Показати всіх користувачів</a></li>
        <li class="nav-item"><%= link_to "Видалити всіх користувачів", remove_all_path, :confirm => "Are you sure?", class: "nav-link", :method => :delete %></li>
      </ul>
    </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lab8RailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<center>
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</center>

app/views/users/new.html.erb
<center>
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>
</center>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>